global using HarmonyLib;
global using MelonLoader;
global using MelonLoader.Utils;
global using MuseDashMirror.Attributes;
global using MuseDashMirror.Attributes.EventAttributes.PatchEvents;
global using MuseDashMirror.Attributes.EventAttributes.SceneEvents;
global using MuseDashMirror.EventArguments;
global using MuseDashMirror.Extensions.UnityExtensions;
global using static MuseDashMirror.UIComponents.Colors;
global using static MuseDashMirror.UIComponents.Fonts;
global using static MuseDashMirror.Utils.GameObjectUtils;
global using static TestMod.MelonBuildInfo;
